services:
  dev:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: example_db
      DB_USER: example_user
      DB_PASSWORD: example_password
      JWT_SECRET: 5ef874dbdbcf8bddd1a44d7d76c16daa23c256a03bb02404aef06b86537afcdd
      
    networks:
      - omegacorp_shared

networks:
  omegacorp_shared:
    external: true