version: '3'
services:
  dev:
    build: .
    ports:
      - '9000:9000'
    volumes:
      - .:/home/app:rw
      - /home/app/node_modules
    restart: 'no'
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
